; ============================================================
;  Gong LoRa CLIENT — PlatformIO configuration
;  Flash as many clients as you need (change CLIENT_ID each time)
; ============================================================
[env:esp32dev]
platform  = espressif32 @ ^6.3.2
board     = esp32dev
framework = arduino

lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    dfrobot/DFRobotDFPlayerMini @ ^1.0.6

monitor_speed = 115200
upload_speed  = 921600

build_flags =
    -DCORE_DEBUG_LEVEL=3
