[env:esp32dev]
platform     = espressif32 @ ^6.3.2
board        = esp32dev
framework    = arduino

monitor_speed  = 115200
upload_speed   = 921600

; SPIFFS: хранит index.html и wifi.conf
board_build.filesystem = spiffs

lib_deps =
    bblanchon/ArduinoJson          @ ^6.21.5
    sandeepmistry/LoRa             @ ^0.8.0
    arduino-libraries/NTPClient    @ ^3.2.1
    dfrobot/DFRobotDFPlayerMini    @ ^1.0.6

build_flags =
    -DCORE_DEBUG_LEVEL=3
